[workspace]
resolver = "2"
members = [
    "lib",
    "2021_RTCSA_dynfed",
    "2020_RTSS_cpc_model_based_algorithm",
    "2014_TPDS_basic_decomposition_based_algorithm",
    "2014_ECRTS_federated_original",
]