name: cache_cargo
description: caching .cargo directory
runs:
  using: composite

  steps:
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          2014_ECRTS_federated_original/target/
          2020_RTSS_cpc_model_based_algorithm/target/
          2021_RTCSA_dynfed/target/
          lib/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-