[package]
name = "rtss_shudai_zhao"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
petgraph = "0.6.3"
lib = { path = "../lib"}
clap = { version = "4.2.4", features = ["derive"] }