[package]
name = "sched_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.160", features = ["derive"] }
serde_yaml = "0.9.21"
petgraph = "0.6.3"
yaml-rust = "0.4.5"